export const weatherCodeMap: { [key: number]: string } = {
  0: "wi-day-sunny",
  1: "wi-day-sunny-overcast",
  2: "wi-day-cloudy",
  3: "wi-cloudy",
  45: "wi-fog",
  48: "wi-fog",
  51: "wi-sprinkle",
  53: "wi-sprinkle",
  55: "wi-sprinkle",
  61: "wi-rain",
  63: "wi-rain",
  65: "wi-rain",
  71: "wi-snow",
  73: "wi-snow",
  75: "wi-snow",
  80: "wi-showers",
  95: "wi-thunderstorm",
}